robot_name: "concert"

# Failsafe information
max_s_stop: 0.2
q_min_allowed: [-3.0, -3.0, -3.0, -3.0, -3.0, -3.0]
q_max_allowed: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0]
v_max_allowed: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
a_max_allowed: [5, 5, 5, 5, 5, 5]
j_max_allowed: [100, 100, 100, 100, 100, 100]
# Maximum long-term planning acc / jerk
a_max_ltt: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
j_max_ltt: [7, 7, 7, 7, 7, 7]

nb_joints: 6

q1: [0.0]
q2: [0.0]
q3: [0.0]
q4: [0.0]
q5: [0.0]
q6: [0.0]
